# update Homebrew
update

# Add Repository
tap josegonzalez/homebrew-php
tap homebrew/binary
tap phinze/homebrew-cask

# Memo:
# autoconf:   emacs with inline.patch needs autoheader
# jq:         json pretty-print
# mcrypt:     for PHP
# openssl:    for ruby
# pkg-config: for gem ref
# qt:         gem capybara-screenshot uses qmake
# readline:   for Ruby
# stunnel:    for mew
# webkit2png: % webkit2png -TF http://masutaka.net
install ack
install aspell
install autoconf
install binutils
install cmigemo
install git
install global
install gnu-sed
install gnupg
install heroku-toolbelt
install imagemagick
install jq
install jsl
install kindlegen
install lv
install markdown
install mcrypt
install mercurial
install nginx
install node
install openssl
install phpenv
install pkg-config
install plenv
install postgresql
install qt
install rbenv
install readline
install stunnel
install unrar
install w3m
install webkit2png
install wget
install xz

install brew-cask
cask install adobe-reader
cask install alfred
cask install appcleaner
cask install coteditor
cask install dropbox
cask install firefox
cask install flash
cask install flip4mac
cask install genymotion
cask install gimp
cask install github
cask install google-chrome
cask install google-drive
cask install grandperspective
cask install handbrake
cask install iterm2
cask install karabiner
cask install libreoffice
cask install limechat
cask install lyn
cask install opera
cask install quicksilver
cask install ripit
cask install sequel-pro
cask install silverlight
cask install skitch
cask install skype
cask install slack
cask install sourcetree
cask install sublime-text
cask install vagrant
cask install virtualbox
cask install vlc
